### ISSUE TITLE
ReferenceError: Unknown plugin "transform-dead-code-elimination"

### ISSUE THREAD

**Issue by lxg** [escompress/escompress#11]
After installing escompress with `npm install -g escompress` and trying it on a test file, I get the following error:

```
ReferenceError: Unknown plugin "transform-dead-code-elimination" specified in "base" at 0, attempted to resolve relative to "."
    at /usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/usr/local/lib/node_modules/escompress/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/escompress/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/usr/local/lib/node_modules/escompress/node_modules/babel-cli/lib/babel/util.js:59:12)
```
I should note that the installation, though successful, gave the following warnings:

```
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
```
Any ideas what the problem might be?

**Comment by imranolas** [comment]
Sadly this project has been abandoned in favor of https://github.com/babel/babili. The good news is that babili has a great team and ton of support behind it.

**Comment by lxg** [comment]
ok, thanks for the heads-up!
